import { Lora } from "next/font/google";
import "./globals.css";
const elsie = Lora({
  subsets: ["latin"],
});

export const metadata = {
  title: "Be My Girlfriend",
  description: "Generated by a man who loves you so much.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={elsie.className}>{children}</body>
    </html>
  );
}
